### ISSUE TITLE
Joysticks updates comm buffer with the wrong values

### ISSUE THREAD

**Issue by javatechs** [javatechs/BStudioGameController#3]
The joystick listener updates comm buffer with the wrong values. It is supposed to use X & Y.
Instead it uses angle and strength.

**Comment by madhephaestus** [comment]
yeah, X,Y is the mode used by the Wii controllers. The range should be 0-255, with 128 as center

**Comment by javatechs** [comment]
https://github.com/javatechs/BStudioGameController/commit/c032222c4dd628a43199f4796281700316d000c6
